name: Verify problems

on: [push]

jobs:
  problems:
    name: Verify ICPC-style problems
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          sudo apt install automake g++ make libboost-regex-dev libgmp-dev libgmp10 libgmpxx4ldbl python3 python3-pytest python3-setuptools python3-yaml python3-plastex python3-unidecode
          python -m pip install --upgrade pip
          pip install git+https://github.com/kattis/problemtools
          pip install -r requirements.txt
          python3 problems/statistics10multiplelinearregression/submissions/accepted/stefan.py < problems/statistics10multiplelinearregression/data/sample/1.in
      - name: Verify problems
        run: (cd problems && make all)
